import { AbilityConstant, UIAbility, Want } from '@kit.AbilityKit';
import { hilog } from '@kit.PerformanceAnalysisKit';
import { window } from '@kit.ArkUI';
import { httpDefaultSetting } from '../api/axios'
import { HMRouterMgr } from '@hadss/hmrouter';
import { LoginInfo } from '../pages/LoginPage';
import { BusinessError } from '@kit.BasicServicesKit';
import { fileUri } from '@kit.CoreFileKit';

export default class EntryAbility extends UIAbility {
  private intervalID: ESObject = null

  onCreate(want: Want, launchParam: AbilityConstant.LaunchParam): void {
    hilog.info(0x0000, 'testTag', '%{public}s', 'Ability onCreate');
    // 初始化 axios 配置
    httpDefaultSetting()

    // 初始路由 HMRouterMgr 框架
    HMRouterMgr.init({
      context: this.context
    })

  }

  onDestroy(): void {
    hilog.info(0x0000, 'c', '%{public}s', 'Ability onDestroy');
    clearInterval(this.intervalID);
  }

  onWindowStageCreate(windowStage: window.WindowStage): void {
    // Main window is created, set main page for this ability
    hilog.info(0x0000, 'testTag', '%{public}s', 'Ability onWindowStageCreate');
    windowStage.loadContent('pages/Index', (err) => {
      if (err.code) {
        hilog.error(0x0000, 'testTag', 'Failed to load the content. Cause: %{public}s', JSON.stringify(err) ?? '');
        return;
      }
      hilog.info(0x0000, 'testTag', 'Succeeded in loading the content.');
      PersistentStorage.persistProp<LoginInfo>('LOGIN_INFO', {})
      PersistentStorage.persistProp<string>('ACCESS_TOKEN', '')
      PersistentStorage.persistProp<string>('REFRESH_TOKEN', '')

      let para: Record<string, number | string> = {
        'onCurrentIndexUpdate': 1,
        'username': '',
        'password': ''
      };
      let storage: LocalStorage = new LocalStorage(para);

      // 设置全屏模式和避让区域
      let windowClass: window.Window = windowStage.getMainWindowSync(); // 获取应用主窗口
      // 1. 设置窗口全屏
      let isLayoutFullScreen = true;
      windowClass.setWindowLayoutFullScreen(isLayoutFullScreen).then(() => {
        console.info('Succeeded in setting the window layout to full-screen mode.');
      }).catch((err: BusinessError) => {
        console.error('Failed to set the window layout to full-screen mode. Cause:' + JSON.stringify(err));
      });
      // 2. 获取当前布局避让遮挡的区域
      let type = window.AvoidAreaType.TYPE_SYSTEM; // 以状态栏避让为例
      let avoidArea = windowClass.getWindowAvoidArea(type);
      let topRectHeight = px2vp(avoidArea.topRect.height); // 获取状态栏区域高度

      AppStorage.setOrCreate('topRectHeight', topRectHeight);
      // 3. 注册监听函数，动态获取避让区域数据
      windowClass.on('avoidAreaChange', (data) => {
        if (data.type === window.AvoidAreaType.TYPE_SYSTEM) {
          let topRectHeight = data.area.topRect.height;
          AppStorage.setOrCreate('topRectHeight', topRectHeight);
        }
      });




    });
  }

  onWindowStageDestroy(): void {
    // Main window is destroyed, release UI related resources
    hilog.info(0x0000, 'testTag', '%{public}s', 'Ability onWindowStageDestroy');
  }

  onForeground(): void {
    // Ability has brought to foreground
    hilog.info(0x0000, 'testTag', '%{public}s', 'Ability onForeground');
  }

  onBackground(): void {
    // Ability has back to background
    hilog.info(0x0000, 'testTag', '%{public}s', 'Ability onBackground');
  }
}
